config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :parties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :planned_parties
  has_many :parties, through: :planned_parties
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :planned_parties
  has_many :guests, through: :planned_parties
end

app/models/planned_party.rb
class PlannedParty < ApplicationRecord
  belongs_to :party
  belongs_to :guest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:first_name, :last_name, :phone, :email)
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:title, :started_at, :ended_at, :address, :city, :state, :zip_code, :phone, :email, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/guests/_form.html.erb
<%= form_for(guest) do |f| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guests</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.first_name %></td>
        <td><%= guest.last_name %></td>
        <td><%= guest.phone %></td>
        <td><%= guest.email %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @guest.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @guest.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @guest.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartyPlanner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parties/_form.html.erb
<%= form_for(party) do |f| %>
  <% if party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :started_at %>
    <%= f.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= f.label :ended_at %>
    <%= f.datetime_select :ended_at %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parties</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Started at</th>
      <th>Ended at</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.title %></td>
        <td><%= party.started_at %></td>
        <td><%= party.ended_at %></td>
        <td><%= party.address %></td>
        <td><%= party.city %></td>
        <td><%= party.state %></td>
        <td><%= party.zip_code %></td>
        <td><%= party.phone %></td>
        <td><%= party.email %></td>
        <td><%= party.url %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @party.title %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @party.started_at %>
</p>

<p>
  <strong>Ended at:</strong>
  <%= @party.ended_at %>
</p>

<p>
  <strong>Address:</strong>
  <%= @party.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @party.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @party.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @party.zip_code %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @party.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @party.email %>
</p>

<p>
  <strong>Url:</strong>
  <%= @party.url %>
</p>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>